### ISSUE TITLE
no compatible build found with meteor 1.0.2.1

### ISSUE THREAD

**Issue by jbl2024** [HedCET/linto-spreadjs#1]
Hi,

when adding the package on a fresh project install (with meteor version 1.0.2.1) i have the following error :

```
~/test/spreadtest $ meteor add linto:spreadjs
 => Errors while adding packages:

While checking for linto:spreadjs@3.20142.16:
error: No compatible build found
```

**Comment by sujith3g** [comment]
Try  `meteor add linto:spreadjs@4.0.2` [this](https://github.com/HedCET/spreadjs/blob/master/.meteor/packages#L16)

**Comment by jbl2024** [comment]
it works, thanks!
